services:
  ollama-model:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ollama-model:latest
    container_name: ollama-model
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_ENDPOINTS=${OLLAMA_ENDPOINTS:-ollama:11434}
